services:
  app-prod:
    container_name: app-container-production
    build:
      context: ./app
      dockerfile: Dockerfile
      target: release
    ports:
      - "3000:3000"
  nginx-prod:
    container_name: nginx-container-production
    build: 
      context: ./nginx
      dockerfile: Dockerfile
      target: release
    ports:
      - "80:80"
    depends_on:
      - app-prod