services:
  app-dev:
    container_name: app-container-development
    build:
      context: ./app
      dockerfile: Dockerfile
      target: development
    ports:
      - "3000:3000"
  nginx-dev:
    container_name: nginx-container-development
    build: 
      context: ./nginx
      dockerfile: Dockerfile
      target: development
    ports:
      - "80:80"
    depends_on:
      - app-dev